# Generated by Django 4.1.7 on 2023-02-17 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0007_employerconfig'),
        ('JobListings', '0002_rename_url_job_posting_url_job_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credentials.employer'),
        ),
    ]
