# Generated by Django 4.1.7 on 2023-02-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0003_job_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
    ]
