# Generated by Django 4.1.7 on 2023-02-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_experience_education_candidateconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateconfig',
            name='resume',
            field=models.BinaryField(null=True),
        ),
    ]
