# Generated by Django 4.1.7 on 2023-02-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0010_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='interests',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
