# Generated by Django 4.1.7 on 2023-02-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0012_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
