# Generated by Django 4.1.7 on 2023-03-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('posting_url', models.TextField()),
                ('posting_date', models.DateField()),
                ('expiry_date', models.DateField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('recruiter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credentials.recruiter')),
            ],
        ),
    ]
