# Generated by Django 4.1.7 on 2023-02-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='url',
            new_name='posting_url',
        ),
        migrations.AddField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=2560),
        ),
    ]
