# Generated by Django 4.1.7 on 2023-03-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('JobListings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicatons',
            fields=[
                ('job_application_id', models.IntegerField(primary_key=True, serialize=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobListings.job')),
            ],
        ),
    ]
