# Generated by Django 4.1.7 on 2023-03-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('JobListings', '0002_jobapplicatons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplicatons',
            new_name='JobApplications',
        ),
    ]
