# Generated by Django 4.1.7 on 2023-02-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0004_remove_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posting_url',
            field=models.TextField(),
        ),
    ]
