# Generated by Django 4.1.7 on 2023-03-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('JobListings', '0004_applications_delete_jobapplications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
