# Generated by Django 4.1.7 on 2023-04-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0005_rename_applications_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_date',
            field=models.DateField(default='2023-04-07'),
        ),
    ]
