# Generated by Django 4.1.7 on 2023-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0006_application_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_accepted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_date',
            field=models.DateField(default='2023-04-08'),
        ),
    ]
