# Generated by Django 4.1.7 on 2023-03-04 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0017_rename_user_id_applicant_user_and_more'),
        ('JobListings', '0006_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credentials.recruiter'),
        ),
    ]
