# Generated by Django 4.1.7 on 2023-04-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0008_rename_position_experience_title'),
        ('JobListings', '0007_application_application_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.recruiter'),
        ),
    ]
