# Generated by Django 4.1.7 on 2023-03-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0007_alter_job_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employer',
            new_name='recruiter',
        ),
    ]
