# Generated by Django 4.1.7 on 2023-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='award_one',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='award_two',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='established',
            field=models.DateField(null=True),
        ),
    ]
