# Generated by Django 4.1.7 on 2023-03-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_applicant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interests',
            field=models.TextField(default=''),
        ),
    ]
