# Generated by Django 4.1.7 on 2023-03-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_alter_applicant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='interests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
