# Generated by Django 4.1.7 on 2023-02-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0007_employerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidateconfig',
            name='interests',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidateconfig',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employerconfig',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='skills',
            field=models.TextField(),
        ),
    ]
