# Generated by Django 4.1.7 on 2023-02-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0008_education_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateconfig',
            name='current_employer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='credentials.employer'),
        ),
    ]
