# Generated by Django 4.1.7 on 2023-02-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0015_alter_applicant_user_alter_recruiter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='user',
            new_name='user_id',
        ),
    ]
