# Generated by Django 4.1.7 on 2023-02-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0016_rename_user_applicant_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='user_id',
            new_name='user',
        ),
    ]
