# Generated by Django 4.1.7 on 2023-03-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0017_rename_user_id_applicant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateconfig',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidateconfig',
            name='current_employer',
        ),
        migrations.RemoveField(
            model_name='employerconfig',
            name='employer',
        ),
        migrations.AlterField(
            model_name='education',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credentials.applicant'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.applicant'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='CandidateConfig',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='EmployerConfig',
        ),
    ]
