# Generated by Django 4.1.7 on 2023-03-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0019_rename_candidate_education_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='username',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='username',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
